# -------------------------
#         ALIASES
# -------------------------

aliases:
  # -------------------------
  #          CACHE
  # -------------------------
  - &restore-yarn-cache
    keys:
      - v4-yarn-cache-{{ arch }}-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}-{{ checksum "tests/package.json" }}-{{ checksum "tests/yarn.lock" }}

  - &save-yarn-cache
    paths:
      - ~/.cache/yarn
      - ~/Library/Detox/ios
    key: v4-yarn-cache-{{ arch }}-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}-{{ checksum "tests/package.json" }}-{{ checksum "tests/yarn.lock" }}

  - &save-pods-cache
    paths:
      - ~/react-native-firebase/tests/ios/Pods
    key: v4-pods-cache-{{ arch }}-{{ checksum "ios/RNFirebase.podspec" }}-{{ checksum "tests/ios/Podfile" }}-{{ checksum "tests/ios/Podfile.lock" }}

  - &restore-pods-cache
    keys:
      - v4-pods-cache-{{ arch }}-{{ checksum "ios/RNFirebase.podspec" }}-{{ checksum "tests/ios/Podfile" }}-{{ checksum "tests/ios/Podfile.lock" }}

  - &save-ios-build-cache
    paths:
      - ~/react-native-firebase/tests/ios/build/Build
    key: v4-ios-build-cache-{{ arch }}-{{ checksum "ios/RNFirebase.podspec" }}-{{ checksum "tests/ios/Podfile" }}-{{ checksum "tests/ios/Podfile.lock" }}

  - &restore-ios-build-cache
    keys:
      - v4-ios-build-cache-{{ arch }}-{{ checksum "ios/RNFirebase.podspec" }}-{{ checksum "tests/ios/Podfile" }}-{{ checksum "tests/ios/Podfile.lock" }}

  - &save-brew-cache
    paths:
      - /usr/local/Homebrew
      - ~/Library/Caches/Homebrew
    key: v4-brew-cache-{{ arch }}

  - &restore-brew-cache
    keys:
      - v4-brew-cache-{{ arch }}

  - &configure-jet-detox-environment
    name: Configure Jet + Detox Environment
    command: |
      brew install node@8 >/dev/null
      brew tap wix/brew >/dev/null
      brew install applesimutils >/dev/null
      brew install watchman >/dev/null
      touch .watchmanconfig
      node -v

  - &packager-jet
    name: Start React Native Pacakager (background)
    background: true
    command: cd tests && yarn run packager-jet || true

  - &packager-warmup
    name: Warming up Packager
    background: true
    command: node .circleci/scripts/packager-warmup.js


  # -------------------------
  #       INSTALLATION
  # -------------------------
  - &yarn
    name: Yarn Install ./ and ./tests
    command: |
      yarn install --non-interactive --cache-folder ~/.cache/yarn
      cd tests && yarn install --non-interactive

  # -------------------------
  #         ANDROID
  # -------------------------

  - &android-create-avd
    name: Create AVD
    command: |
      sdkmanager "$AVD_PACKAGE"
      avdmanager create avd --name "$AVD_NAME" --force --package "$AVD_PACKAGE" --tag google_apis --abi "$AVD_ABI"

  - &android-launch-avd
    name: Launch AVD
    background: true
    command: |
      "$ANDROID_HOME/emulator/emulator" -avd "$AVD_NAME" -no-audio -no-window

  - &android-wait-avd
    name: Wait for AVD to be ready
    background: true
    command: ./.circleci/scripts/wait-for-avd.sh


  # -------------------------
  #         ANALYSE
  # -------------------------

  # eslint
  - &eslint
    name: Lint Code
    command: yarn run lint

  # flow
  - &validate-flow-declarations
    name: Validate Flow Declarations
    command: yarn run validate-flow-declarations

  # typescript
  - &validate-ts-declarations
    name: Validate TypeScript Declarations
    command: yarn run validate-ts-declarations

# -------------------------
#        DEFAULTS
# -------------------------
defaults: &defaults
  working_directory: ~/react-native-firebase
  environment:
    - GIT_COMMIT_DESC: git log --format=oneline -n 1 $CIRCLE_SHA1

# JAVASCRIPT
js_defaults: &js_defaults
  <<: *defaults
  docker:
    - image: circleci/node:8
  environment:
    - PATH: "/opt/yarn/yarn-v1.5.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# ANDROID
android_defaults: &android_defaults
  <<: *defaults
  docker:
    - image: reactnativecommunity/react-native-android
  resource_class: "large"
  working_directory: ~/react-native-firebase
  environment:
    - ADB_INSTALL_TIMEOUT: 10
    - _JAVA_OPTIONS: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Xmx2000m"
    - GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-XX:+HeapDumpOnOutOfMemoryError"'
    - BUILD_THREADS: 2
    - AVD_ABI: "armeabi-v7a"
    - AVD_NAME: "TestingAVD"
    - AVD_PACKAGE: "system-images;android-19;google_apis;$AVD_ABI"

# IOS
macos_defaults: &macos_defaults
  <<: *defaults
  resource_class: "medium"
  macos:
    xcode: "10.1.0"

# -------------------------
#          JOBS
# -------------------------
version: 2
jobs:
  # Set up a Node environment for downstream jobs
  checkout-code:
    <<: *js_defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .

  analyse:
    <<: *js_defaults
    steps:
      - attach_workspace:
          at: ~/react-native-firebase
      - restore-cache: *restore-yarn-cache
      - run: *yarn
      - save-cache: *save-yarn-cache
      - run: *eslint
      - run: *validate-flow-declarations
      - run: *validate-ts-declarations

  android-test-e2e:
    <<: *android_defaults
    steps:
      - setup_remote_docker:
          docker_layer_caching: true

      - attach_workspace:
          at: ~/react-native-firebase

      - restore-cache: *restore-yarn-cache
      - run: *yarn
      - save-cache: *save-yarn-cache

      - run: *android-create-avd
      - run: *android-launch-avd

      - restore_cache:
          key: v1-gradle-{{ checksum "tests/android/build.gradle" }}-{{ checksum  "tests/android/app/build.gradle" }}-{{ checksum  "android/build.gradle" }}
      - run:
          name: Build Android Testing App
          command: cd tests/android && chmod +x gradlew && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug
      - save_cache:
          paths:
            - ~/react-native-firebase/tests/android/.gradle
          key: v1-gradle-{{ checksum "tests/android/build.gradle" }}-{{ checksum  "tests/android/app/build.gradle" }}-{{ checksum  "android/build.gradle" }}

      - run: *android-wait-avd

  android-build-release:
    <<: *android_defaults
    steps:
      - setup_remote_docker:
          docker_layer_caching: true

      - attach_workspace:
          at: ~/react-native-firebase

      - restore-cache: *restore-yarn-cache
      - run: *yarn
      - save-cache: *save-yarn-cache

      - restore_cache:
          key: v1-release-gradle-{{ checksum "tests/android/build.gradle" }}-{{ checksum  "tests/android/app/build.gradle" }}-{{ checksum  "android/build.gradle" }}
      - run:
          name: Build Android Release APK
          command: cd tests/android && chmod +x gradlew && ./gradlew assembleRelease
      - save_cache:
          paths:
            - ~/react-native-firebase/tests/android/.gradle
          key: v1-release-gradle-{{ checksum "tests/android/build.gradle" }}-{{ checksum  "tests/android/app/build.gradle" }}-{{ checksum  "android/build.gradle" }}


  ios-test-e2e:
    <<: *macos_defaults
    steps:
      - attach_workspace:
          at: ~/react-native-firebase
      - run:
          name: Start iPhone X simulator (background)
          background: true
          command: xcrun simctl boot "iPhone X" || true
      - run:
          name: Configure Environment Variables
          command: |
            echo 'export PATH=/usr/local/opt/node@8/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
      # Brew
      - restore-cache: *restore-brew-cache
      - run: *configure-jet-detox-environment
      - save-cache: *save-brew-cache

      # Yarn install - to ensure detox post install builds
      - restore-cache: *restore-yarn-cache
      - run: *yarn
      - save-cache: *save-yarn-cache

      # Pods
      - restore-cache: *restore-pods-cache
      - run:
          name: Install CocoaPods +  Pod Install
          command: |
            cd tests/ios
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
            pod install
      - save-cache: *save-pods-cache

      # must always be after environment config job but before ios build
      - run: *packager-jet
      - run: *packager-warmup

      # XCode Build
      - restore-cache: *restore-ios-build-cache
      - run:
          name: Build iOS Testing App
          command: cd tests && yarn run build-ios
      - save-cache: *save-ios-build-cache

      - run: mkdir ~/detox-artifacts

      # Now Test \o/
      - run:
          name: Run Jet Tests
          command: cd tests && yarn run test-ios-cover

      # TODO merge coverage output from android and iOS
      - run:
          name: Submit Coverage
          command: yarn run codecov

      - store_artifacts:
          path: ~/detox-artifacts
      - store_artifacts:
          path: ~/react-native-firebase/coverage


# -------------------------
#        WORK FLOWS
# -------------------------
workflows:
  version: 2
  Test:
    jobs:
      - checkout-code

      - analyse:
          requires:
            - checkout-code

      - android-test-e2e:
          requires:
            - checkout-code
            - analyse

#      - android-build-release:
#          requires:
#            - checkout-code
#            - analyse

#    - ios-test-e2e:
#        requires:
#        - checkout-code
#        - analyse
